version: "3.7"
networks:
    proxy:
        driver: bridge
services:
    all-spark-notebook:
        build:
            context: ./docker
            dockerfile: Dockerfile.spark
        ports:
            - "8888:8888"
            - "4040:4040"
        networks:
            - proxy
        volumes:
            - $PWD:/home/jovyan/work
    postgres:
        image: postgres:12.2
        networks:
            - proxy
        env_file:
            - ./docker/postgres.env
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
# pyspark --packages org.postgresql:postgresql:42.2.12
